created dashboard overview document
checkly/checklyhq.com pull request #100
Opened 2021-07-07 15:58 UTC by josep-fl

Created dashboard overview page

2021-07-08 11:20 UTC, ragog requested changes
@josep-fl please see my comments. I have added some directions but I expect you to go through these pages in-depth and propose improvements on your own.

2021-07-08 11:20 UTC, ragog commented on site/content/docs/dashboards/dashboard-url.md
> +Checkly dashboards are public dashboards available on every plan. Use them on your wall mounted TVs, on
Maybe the URL & Custom Domain page should just get absorbed into Overview?

2021-07-08 11:20 UTC, ragog commented on site/content/docs/dashboards/dashboard-url.md
> +> Dashboards can be **embedded in iframes**.
Let's move this down, below the next phrase ("You can create multiple...").

2021-07-08 11:20 UTC, ragog commented on site/content/docs/dashboards/_index.md
> +title: Overview
This page should show at least an example screenshot of a complete dashboard. We are talking about dashboards in this section without ever showing what they look like.

2021-07-14 08:34 UTC, ragog requested changes
@josep-fl getting there, just a couple of changes needed in the new section.

2021-07-14 08:34 UTC, ragog commented on site/content/docs/dashboards/_index.md
> +In order to show specific checks in a dashboard, you will need to do this:
@josep-fl this whole section still reads like a support ticket, can we improve it?

2021-07-14 08:34 UTC, ragog commented on site/content/docs/dashboards/_index.md
> +In order to show specific checks in a dashboard, you will need to do this:
Also, let's make it clear that all checks are automatically shown if we do not specify exactly which ones to include.

2021-07-19 17:22 UTC, ianaya89 commented
Looks good to me. Just one comment:
@josep-fl would be great to use [commitizen style](https://github.com/commitizen/cz-cli) for commits to keep consistency
![image](https://user-images.githubusercontent.com/3258966/126200948-1ea75396-a6fa-4bd5-a0f9-ca3ee0918691.png)

2021-07-19 18:07 UTC, ragog commented on site/content/docs/dashboards/_index.md
> +By default, if no check is specified, all checks in the account will be shown in the dashboard. If instead you want to show show specific checks, this is how it's accomplished:
Typo: "show show"

2021-07-19 18:07 UTC, ragog commented on site/content/docs/dashboards/_index.md
> +You'll need to press Enter to save the tag before you save your updated check!
I think the 1. & 2. points mess up the page a bit with the indentation (it looks more confusing than it should). My 2 cents.

2021-07-20 15:15 UTC, ragog approved these changes
LGTM @josep-fl

2021-07-20 15:18 UTC, merged