Add case studies section to menu dropdown
checkly/checklyhq.com pull request #210
Opened 2021-09-30 14:52 UTC by pilimartinez

Resolves #208 

- [ ] Add case studies section to menu dropdown

2021-09-30 15:27 UTC, ianaya89 requested changes
Looks good, just a minor change.

2021-09-30 15:27 UTC, ianaya89 commented on src/scss/checkly-webapp-src/style/scss/components/_dropdowns.scss
> +        padding-top: 0px;
This could be just `0`

2021-09-30 15:27 UTC, ianaya89 commented on site/layouts/partials/navbar.html
> +                      <div class="menu-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
`lorem` here, do we have the final version? cc @orcunilbeyli

2021-09-30 16:52 UTC, pilimartinez commented on src/scss/checkly-webapp-src/style/scss/components/_dropdowns.scss
> +        padding-top: 0px;
fixed :)

2022-03-07 14:58 UTC, ianaya89 commented
@orcunilbeyli what should we do with this?

2022-07-23 21:08 UTC, closed without merging