docs: WIP: SSO section
checkly/checklyhq.com pull request #45
Opened 2021-04-30 11:20 UTC by ragog

2021-04-30 13:26 UTC, ragog commented on site/content/docs/single-sign-on/_index.md
> +---
@ianaya89 do you know why this page is not showing on the sidebar under "Single sign-on", in the docs? Played around with it but couldn't figure it out yet.

2021-05-03 11:29 UTC, tnolet requested changes
Looks & reads great. Just one niggle with a broken image

2021-05-03 11:29 UTC, tnolet commented on site/content/docs/single-sign-on/microsoft-azure-ad.md
> +![checkly login prompt without password screenshot](/docs/images/single-sign-on/checkly-login-prompt-sso.png)
This image seems to be broken

2021-05-04 09:58 UTC, tnolet approved these changes
LGTM

2021-05-04 10:00 UTC, merged