Create docs for Playwright Test (Beta)
checkly/checklyhq.com pull request #527
Opened 2022-09-29 15:44 UTC by darkostanimirovic

## Affected Components
* [ ] Content & Marketing
* [ ] Test
* [x] Docs
* [ ] Learn
* [ ] Other

## Pre-Requisites
* [ ] Code is linted (`npm run lint`)

## Notes for the Reviewer
- Still a draft, I haven't finished all the pieces.
- I want to look into good images or video but not sure I'll get to that this week.
- Since this is a Public Beta, it's OK that it's a little simplistic. It will still give enough information, especially the list of supported/unsupported features.

2022-10-10 14:39 UTC, darkostanimirovic commented
@checklyalex Can you take a look now? I'm a little unsure about the GIFs. Do we have like a standard for how these should look? Eventually these should probably be actual YT videos right?

2022-10-11 11:26 UTC, checklyalex commented on site/content/docs/browser-checks/playwright-test.md
> +Playwright test is currently only available on the latest runtime, 2022.02.
Let's make sure 'Playwright Test' is always capitalised.

2022-10-11 11:27 UTC, checklyalex commented on site/content/docs/browser-checks/playwright-test.md
> +Here's an example of a Playwright test script that fails, and provides a video of the test sequence.
Same again here

2022-10-11 11:34 UTC, checklyalex requested changes
Looks good enough to get us started. We need to strip out of the purple from the videos to [keep the look and feel consistent](https://www.notion.so/checkly/WIP-Docs-Style-Guide-69f5792000464e398b68a45c3fb4042a#db82436457a24cd09161e7a328dda205). If you can do that before tomorrow, it would be great. If not, we can get this out.

2022-10-11 11:34 UTC, checklyalex commented on site/content/docs/browser-checks/playwright-test.md
> +All it takes from there is to create a new browser check and write a Playwright Test script:
```suggestion
A simple Playwright Test script would look like this:
```

2022-10-11 11:34 UTC, checklyalex commented on site/content/docs/browser-checks/playwright-test.md
> +Here's an example of a Playwright test script that fails, and provides a video of the test sequence.
```suggestion
Here's an example of a Playwright Test script that fails, and provides a video of the test sequence.
```

2022-10-11 11:34 UTC, checklyalex commented on site/content/docs/browser-checks/playwright-test.md
> +Playwright test is currently only available on the latest runtime, 2022.02.
```suggestion
Playwright Test is currently only available on the latest runtime, 2022.02.
```

2022-10-11 13:30 UTC, darkostanimirovic commented
@checklyalex I've updated the GIFs, can you take a look now? I used the Guest mode.

2022-10-12 09:10 UTC, checklyalex approved these changes
LGTM

2022-10-13 08:21 UTC, merged