docs: update PWT page [sc-13036]
checkly/checklyhq.com pull request #605
Opened 2023-01-03 12:36 UTC by miliberlin

## Affected Components
* [ ] Content & Marketing
* [ ] Pricing
* [ ] Test
* [x] Docs
* [ ] Learn
* [ ] Other

## Pre-Requisites
* [ ] Code is linted (`npm run lint`)

## Notes for the Reviewer

Preview at `docs/browser-checks/playwright-test`

## New Dependency Submission

## Screenshots

2023-01-03 14:31 UTC, pilimartinez requested changes
Just a small typo, the rest looks good.

2023-01-03 14:31 UTC, pilimartinez commented on site/content/docs/browser-checks/playwright-test.md
> +Read more on how to usitilise Playwright Test best in the [official documentation](https://playwright.dev/docs/writing-tests).
Is usitilise a typo from utilise?

2023-01-03 15:53 UTC, pilimartinez submitted a review, later dismissed
LGTM

2023-01-03 16:46 UTC, jan-osch submitted a review, later dismissed
❤️

2023-01-03 16:46 UTC, jan-osch commented on site/content/docs/browser-checks/playwright-test.md
> +> regardless of whether the check is passing or failing. For scheduled checks files are only preserved when the check failed.
```suggestion
> regardless of whether the check is passing or failing. For scheduled check runs videos and traces are only preserved when the check failed.
```

2023-01-03 16:46 UTC, jan-osch commented on site/content/docs/browser-checks/playwright-test.md
In the table above: can you mention that TS can be enabled via labs w/ link?

2023-01-04 13:23 UTC, jan-osch approved these changes
Looks great!

2023-01-04 13:52 UTC, merged