feat: update check results page with retries [sc-14874]
checkly/checklyhq.com pull request #791
Opened 2023-04-25 11:07 UTC by miliberlin

## Affected Components
* [ ] Content & Marketing
* [ ] Pricing
* [ ] Test
* [x] Docs
* [ ] Learn
* [ ] Other

## Pre-Requisites
* [ ] Code is linted (`npm run lint`)

## Notes for the Reviewer

## New Dependency Submission

## Screenshots

2023-04-25 11:26 UTC, adamwardecki requested changes
One nit

2023-04-25 11:26 UTC, adamwardecki commented on site/content/docs/monitoring/check-results.md
> +By selecting a check run all data and assets are available for inspection for each attempt.
```suggestion
When selecting a check run, all data and assets are available for inspection for each attempt.
```

2023-04-25 13:29 UTC, drakirnosslin approved these changes
Looks good 👍 
Added a few nitpicks, but they are minor.

2023-04-25 13:29 UTC, drakirnosslin commented on site/content/docs/monitoring/check-results.md
> +The summary at the top of the page allows for filtering based on all of the page's data points and the selected timeframe and locations. Retried check runs do not influence this section and only fina
Suggestion for conciseness. 
```suggestion
The summary at the top of the page allows for filtering based on the page's data points and the selected timeframe and locations. Retried check runs do not influence this section; only the final results are considered.
```

2023-04-25 13:29 UTC, drakirnosslin commented on site/content/docs/monitoring/check-results.md
> +The check retries ratio indicates how many of the total checks run were executed twice due to an initial failed attempt.
I'm not sure I like this suggestion more TBH - it's just a way to get around having to update this again if we add the capability of having more than 1 retry per check run.
```suggestion
The check retries ratio indicates how many of the total checks run were retried due to an initial failed attempt.
```

2023-04-25 13:29 UTC, drakirnosslin commented on site/content/docs/monitoring/check-results.md
> +When retries are enabled through the "Double-check on failure" setting, tabs will indicate that the check result contains multiple check runs:
```suggestion
When retries are enabled through the "[Double-check on failure](/docs/alerting/#double-checking)" setting, tabs will indicate that the check result contains multiple check runs:
```

2023-04-27 08:44 UTC, drakirnosslin submitted a review, later dismissed

2023-05-10 15:08 UTC, adamwardecki reviewed
Looks like a good opportunity to update two other screenshots on this page.

2023-05-10 16:53 UTC, drakirnosslin submitted a review, later dismissed

2023-05-11 08:08 UTC, adamwardecki approved these changes

2023-05-11 14:21 UTC, merged