private locations: take another pass
checkly/checklyhq.com pull request #832
Opened 2023-06-26 07:44 UTC by benben

## Affected Components
* [x] Docs

## Notes for the Reviewer
Improved Private Locations and Checkly Agent docs to make them more concise and precise.

2023-06-28 09:09 UTC, tnolet requested changes
Two nits:
- extra space after period
- can you remove the stray ` backticks on all the code blocks? There are a couple

2023-06-28 09:47 UTC, benben commented on site/content/docs/private-locations/_index.md
> +A Private Location is an additional location in Checkly. It acts exactly like any other location, but you run it on your own infrastructure.A Private Location can be used to run checks on your servic
```suggestion
A Private Location is an additional location in Checkly. It acts exactly like any other location, but you run it on your own infrastructure. A Private Location can be used to run checks on your services which are not direcrtly exposed to the public internet but in your own segregated network. To operate a Private Location you need to run at least one Checkly Agent.
```

2023-06-28 09:50 UTC, tnolet requested changes
one more nit

2023-06-28 09:50 UTC, tnolet commented on site/content/docs/private-locations/checkly-agent-configuration.md
>  ```bash
Still some trailing ` in this one

2023-06-29 06:06 UTC, benben commented on site/content/docs/private-locations/checkly-agent-configuration.md
>  enough agent containers up and running based on your workload. Using your container management tool, start new agents with the new API key:
```suggestion
6. You now need to replace your Checkly agents. You can do this one-by-one or as a group, just make sure you always have enough agent containers up and running based on your workload. Using your container management tool, start new agents with the new API key:
```

2023-06-29 08:14 UTC, tnolet approved these changes
LGTM!

2023-06-29 08:14 UTC, merged