feat: rewrite plausible script [ch-00]
checkly/checklyhq.com pull request #92
Opened 2021-06-28 21:32 UTC by ndom91

So this was a little trick I found in the plausible / vercel docs. It is kindddd of morally dubious, as we're actively going around users who use ad-blocking systems. But i don't find it that bad and plausible noted between 6%-29% of users have adblocking enabled (we're probably on the higher side with tech-savvy users).

So its up to you guys if we should merge this or not. If we do, the client will request `/a/b.js` on our own domain and vercel will do the work of serving `https://plausible.io/js/plausible.js` in its place.

2021-06-28 21:48 UTC, ianaya89 commented
I really like this, looks like a clever workaround but as we are open source here I think we should respect if the user wants to avoid tracking.

I pass the ball to @tnolet

2021-06-29 06:32 UTC, hlenke commented
LGTM
Plausible is collecting very few metrics and this should be acceptable and will enable us to stay away from Google Analytics and similar tools.

2021-06-29 07:56 UTC, tnolet commented
I don't approve of anything that tricks a user. Opting out of tracking is something we need to embrace instead of work around.

2021-06-29 07:56 UTC, tnolet requested changes
Let's not do this. I don't we think we should ever trick a user or side steps the opt in / opt out option.

2021-06-29 08:23 UTC, tnolet approved these changes
Ok, just had a chat. Turn out Plausible does not set any cookies and this is just for 3rd party ad blockers. I think it is actually therefore fine to load this from our own domain and use Plausible, which is a privacy conscious solution.

2021-06-29 12:24 UTC, merged